<<<<<<< HEAD
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: test
stringData:
  postgres-secret-parameters: |
    path: postgresql+psycopg://postgres:mysecretpassword@127.0.0.1:55001/feast
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
      echo: false
      pool_pre_ping: true
  postgres: |
    host: 127.0.0.1
    port: 55001
    database: feast
    db_schema: public
    user: postgres
    password: mysecretpassword
---
=======
>>>>>>> 863a82cb7 (feat: Added feast Go operator db stores support (#4771))
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: example
  namespace: test
spec:
  feastProject: my_project
  services:
    onlineStore:
      persistence:
        store:
          type: postgres
          secretRef:
<<<<<<< HEAD
<<<<<<< HEAD
            name: postgres-secret
=======
            name: postgres-secret
          secretKeyName: postgres-secret-parameters   # optional
>>>>>>> 966b02846 (feat: Updated feast Go operator db stores (#4809))
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: postgres-secret
<<<<<<< HEAD
            secretKeyName: postgres-secret-parameters   # optional, will use store.type by default as the SecretKeyName if none is specified, in this case that's "sql"
=======
            name: my-secret
          secretKeyName: mykey   # optional
>>>>>>> 863a82cb7 (feat: Added feast Go operator db stores support (#4771))
=======
            secretKeyName: postgres-secret-parameters   # optional
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
stringData:
  postgres-secret-parameters: |
    path: postgresql+postgresql://postgres:mysecretpassword@127.0.0.1:55001/feast
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
      echo: false
      pool_pre_ping: true
  postgres: |
    host: 127.0.0.1
    port: 55001
    database: feast
    db_schema: public
    user: postgres
    password: mysecretpassword
>>>>>>> 966b02846 (feat: Updated feast Go operator db stores (#4809))
