apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: sample-pvc-persistence
spec:
  feastProject: my_project
  services:
<<<<<<< HEAD
    # demonstrates using a pre-existing PVC
=======
>>>>>>> 6c1a66ea8 (feat: PVC configuration and impl (#4750))
    onlineStore:
      persistence:
        file:
          path: online_store.db
          pvc:
            ref:
              name: online-pvc
            mountPath: /data/online
<<<<<<< HEAD
    # demonstrates specifying a storageClassName and storage size
=======
>>>>>>> 6c1a66ea8 (feat: PVC configuration and impl (#4750))
    offlineStore:
      persistence:
        file:
          type: duckdb
          pvc:
            create:
              storageClassName: standard
              resources:
                requests:
                  storage: 5Gi
            mountPath: /data/offline
<<<<<<< HEAD
    # demonstrates letting the Operator create a PVC w/ defaults set
=======
>>>>>>> 6c1a66ea8 (feat: PVC configuration and impl (#4750))
    registry:
      local:
        persistence:
          file:
            path: registry.db
            pvc:
              create: {}
              mountPath: /data/registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: online-pvc
spec:
  accessModes:
<<<<<<< HEAD
    - ReadWriteOnce
=======
    - ReadWriteMany
>>>>>>> 6c1a66ea8 (feat: PVC configuration and impl (#4750))
  resources:
    requests:
      storage: 5Gi
